import fs from 'fs'

const gamesData = JSON.parse(fs.readFileSync('api-games.json', 'utf8')).games || []
const stadiumsData = JSON.parse(fs.readFileSync('api-stadiums.json', 'utf8')).stadiums || []
const teamsData = JSON.parse(fs.readFileSync('api-teams.json', 'utf8')).teams || []

const teamMap = new Map()
teamsData.forEach(t => teamMap.set(t.id, t))

const stadiumMap = new Map()
stadiumsData.forEach(s => stadiumMap.set(s.id, s))

function parseDate(dateStr) {
    const [datePart, timePart] = dateStr.split(' ')
    const [month, day, year] = datePart.split('/')
    return `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}T${timePart}:00.000Z`
}

let tsOutput = `// Auto-generated by scripts/generate-wc-data.mjs
export interface TeamData {
    id: string
    name: string
    code: string
    iso2: string
    group: string
}

export const TEAMS: TeamData[] = [\n`

teamsData.forEach(t => {
    tsOutput += `    { id: "${t.id}", name: "${t.name_en}", code: "${t.fifa_code}", iso2: "${t.iso2.toLowerCase()}", group: "${t.groups}" },\n`
})
tsOutput += `]\n\n`

tsOutput += `export const GROUPS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'] as const\n`
tsOutput += `export type GroupName = typeof GROUPS[number]\n\n`

tsOutput += `export interface MatchData {
    id: string
    group_label: string
    match_number: number
    home_team: string
    away_team: string
    home_flag: string
    away_flag: string
    kickoff: string
    venue: string
    city: string
    api_id: string // The real API id from worldcup26.ir
}\n\n`

const groupGames = gamesData.filter(g => g.type === 'group')
const knockoutGames = gamesData.filter(g => g.type !== 'group')

const groupMatchArray = []
const groups = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']

groups.forEach(g => {
    const matchesInGroup = groupGames.filter(m => m.group === g)
    matchesInGroup.sort((a, b) => new Date(parseDate(a.local_date)).getTime() - new Date(parseDate(b.local_date)).getTime())
    
    matchesInGroup.forEach((m, idx) => {
        const localId = `${g.toLowerCase()}${idx + 1}`
        const homeTeam = teamMap.get(m.home_team_id)
        const awayTeam = teamMap.get(m.away_team_id)
        const stadium = stadiumMap.get(m.stadium_id)
        
        groupMatchArray.push({
            id: localId,
            api_id: m.id,
            group_label: g,
            match_number: parseInt(m.id),
            home_team: homeTeam ? homeTeam.fifa_code : 'TBD',
            away_team: awayTeam ? awayTeam.fifa_code : 'TBD',
            home_flag: homeTeam ? homeTeam.iso2.toLowerCase() : '🏳️',
            away_flag: awayTeam ? awayTeam.iso2.toLowerCase() : '🏳️',
            kickoff: parseDate(m.local_date),
            venue: stadium ? stadium.name_en : 'TBA',
            city: stadium ? `${stadium.city_en}, ${stadium.country_en}` : 'TBA'
        })
    })
})

tsOutput += `export const GROUP_MATCHES: MatchData[] = ${JSON.stringify(groupMatchArray, null, 4)}\n\n`

const koMatchArray = []
const types = ['r32', 'r16', 'qf', 'sf', '3rd', 'final']
types.forEach(type => {
    const matchesInType = knockoutGames.filter(m => m.type === type)
    matchesInType.sort((a, b) => new Date(parseDate(a.local_date)).getTime() - new Date(parseDate(b.local_date)).getTime())
    
    matchesInType.forEach((m, idx) => {
        let localId = ''
        if (type === '3rd') localId = '3rd'
        else if (type === 'final') localId = 'final'
        else localId = `${type}_${idx + 1}`
        
        const stadium = stadiumMap.get(m.stadium_id)
        let homeLabel = m.home_team_label || 'TBD'
        let awayLabel = m.away_team_label || 'TBD'
        
        koMatchArray.push({
            id: localId,
            api_id: m.id,
            group_label: type.toUpperCase(),
            match_number: parseInt(m.id),
            home_team: homeLabel,
            away_team: awayLabel,
            home_flag: '🏳️',
            away_flag: '🏳️',
            kickoff: parseDate(m.local_date),
            venue: stadium ? stadium.name_en : 'TBA',
            city: stadium ? `${stadium.city_en}, ${stadium.country_en}` : 'TBA'
        })
    })
})

tsOutput += `export const KNOCKOUT_MATCHES: MatchData[] = ${JSON.stringify(koMatchArray, null, 4)}\n\n`

tsOutput += `
export function getTeam(codeOrName: string): TeamData | undefined {
    return TEAMS.find(t => t.code === codeOrName || t.name === codeOrName)
}

export function getGroupMatches(group: string) {
    return GROUP_MATCHES.filter(m => m.group_label === group)
}

export function getFlagUrl(teamCode: string): string | undefined {
    const t = getTeam(teamCode)
    if (!t) return undefined
    // For TBD or non-iso2, we can just return undefined or a generic flag
    if (t.iso2 === '🏳️' || t.iso2 === '') return undefined
    return "https://flagcdn.com/w80/" + t.iso2 + ".png"
}

export const POINTS = {
    EXACT_SCORE: 15,
    CORRECT_RESULT: 5,
    R16_PICK: 10,
    QF_PICK: 15,
    SF_PICK: 20,
    FINAL_PICK: 30,
    CHAMPION: 50,
    EARLY_LOCK: 2,
}

export const BRACKET_ROUNDS = ['r32', 'r16', 'qf', 'sf', 'final', 'champion'] as const
export type BracketRound = typeof BRACKET_ROUNDS[number]

export const R32_SLOTS: Array<[string, string]> = [
    ['2A', '2B'],
    ['1C', '2F'],
    ['1E', 'T3'],
    ['1F', '2C'],
    ['2E', '2I'],
    ['1I', 'T3'],
    ['1A', 'T3'],
    ['1L', 'T3'],
    ['1G', 'T3'],
    ['1D', 'T3'],
    ['1H', '2J'],
    ['2K', '2L'],
    ['1B', 'T3'],
    ['2D', '2G'],
    ['1J', '2H'],
    ['1K', 'T3'],
]

export const ACHIEVEMENTS = [
    { id: 'sharpshooter', icon: '🎯', label: 'Sharpshooter', description: '3 exact scores in one round' },
    { id: 'hot_streak', icon: '🔥', label: 'Hot Streak', description: '5 correct results in a row' },
    { id: 'giant_killer', icon: '⚡', label: 'Giant Killer', description: 'Correctly predict 3 upsets' },
    { id: 'recruiter', icon: '🤝', label: 'The Recruiter', description: 'Create a group with 5+ players' },
    { id: 'score_oracle', icon: '🔢', label: 'Score Oracle', description: '10 exact scores total' },
    { id: 'pole_position', icon: '📈', label: 'Pole Position', description: 'Lead your group at end of group stage' },
    { id: 'contrarian', icon: '🧠', label: 'The Contrarian', description: 'Outpredict the community 10 times' },
    { id: 'perfect_day', icon: '✨', label: 'Perfect Day', description: 'All matches on a single day correct' },
    { id: 'hat_trick_hero', icon: '🎩', label: 'Hat-trick Hero', description: '3 exact scores in 3 consecutive matches' },
    { id: 'final_whistle', icon: '🏟️', label: 'Final Whistle', description: 'Predict the WC Final exact score' },
    { id: 'the_oracle', icon: '🔮', label: 'The Oracle', description: 'Top 1% accuracy globally' },
    { id: 'nostradamus', icon: '👑', label: 'Nostradamus', description: 'Predict the champion correctly' },
]
`

fs.writeFileSync('src/lib/wc2026-data.ts', tsOutput)
console.log('Successfully wrote src/lib/wc2026-data.ts')
